### ISSUE TITLE
I have this problem when I want to open my hub server, it opens the bungee cord but I don't let the hub open, this error appears and it restarts

### ISSUE THREAD

**Issue by bungeees** [ME1312/VanillaCord#21]
Starting server...
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Loading libraries, please wait...
java.lang.ExceptionInInitializerError
        at org.bukkit.craftbukkit.Main.main(Main.java:187)
Caused by: java.lang.UnsupportedOperationException: No class provided, and an appropriate one cannot be found.
        at org.apache.logging.log4j.LogManager.callerClass(LogManager.java:573)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:598)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:585)
        at net.minecraft.server.v1_8_R3.MinecraftServer.<clinit>(Unknown Source)
        ... 1 more

**Comment by ME1312** [comment]
VanillaCord shouldn't be used to patch non-vanilla server software. 😅

If you already knew that, then I'm not sure why you're reporting this issue to the VanillaCord repo. That said, the issue is most likely that you're not running that software under a period-appropriate java version.
