### ISSUE TITLE
Crash when trying to compilate 1.14.2 server

### ISSUE THREAD

**Issue by Thepyrocrafteur** [ME1312/VanillaCord#4]
### What Happened
```java
root@5350:/home/twix/vanillacord# java -jar VanillaCord.jar 1.14.2
VanillaCord launcher v1.6
Searching versions
Reusing patches from branch 1.12
Loading
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.ME1312.VanillaCordLauncher.Launch.main(Launch.java:90)
Caused by: java.lang.NullPointerException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:153)
        at uk.co.thinkofdeath.vanillacord.Main.main(Main.java:90)
        ... 5 more
```
1.14.0 and 1.14.1 build as intended but not way to build 1.14.2.
Is Mojang guilty in this issue?

**Comment by Thepyrocrafteur** [comment]
Ok solved, corrupted download.
