### ISSUE TITLE
Crash with 1.16.4+

### ISSUE THREAD

**Issue by Frogperson** [ME1312/VanillaCord#6]
Running `java -jar VanillaCord.jar 1.16.4` (or the latest snapshot, 20w45a) results in a crash
```
VanillaCord launcher v1.6
Searching versions
Reusing patches from branch 1.12
Loading
Found the login listener in aba.class
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.ME1312.VanillaCordLauncher.Launch.main(Launch.java:90)
Caused by: java.lang.NullPointerException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:153)
        at uk.co.thinkofdeath.vanillacord.Main.main(Main.java:90)
        ... 5 more
```
This does not happen with 1.16.3 or other previous versions.

**Comment by ME1312** [comment]
This issue has been fixed by the above merge request.
Remove the cached `1.12-patch.jar` from the `in` folder to get a new version.
