### ISSUE TITLE
21w19a Update needed cuz java 16?

### ISSUE THREAD

**Issue by ComPieter1** [ME1312/VanillaCord#9]
### What Happened
With the new update 21w19a it doesn't patch anymore likely due to the new java 16 requirement.

### How It Happened
Cuz the new update (21w19a)

### Additional Information
VanillaCord branch 1.12
Searching versions
Downloading Minecraft Server 21w19a
Loading
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at uk.co.thinkofdeath.vanillacord.Launch.main(Launch.java:52)
Caused by: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:153)
        at uk.co.thinkofdeath.vanillacord.Main.main(Main.java:66)
        ... 5 more

**Comment by ME1312** [comment]
Yep, it looks like we're probably going to need to update to ASM 9 to get this branch working in the newer versions. The only problem with that is we're several major versions behind, and there have been meaningful API changes.

If anyone wants to give implementing it a shot, the updated library is the following: (paste over the old one in `build.gradle`)
```
    compile group: 'org.ow2.asm', name: 'asm', version: '9.1'
    compile group: 'org.ow2.asm', name: 'asm-commons', version: '9.1'
```

**Comment by ME1312** [comment]
Looks like this wasn't nearly as difficult a task as it appeared to be. The changes are actually quite minor if you know what you're doing. As a reminder, remember to delete the old 1.12 branch file from your `in` folder before trying again.

As a side note, I don't really know if what I'm about to commit is going to work in the snapshot versions. It looks like it works, but I don't have a snapshot proxy. If it doesn't, then open another issue.

**Comment by ComPieter1** [comment]
Thank you I will look.

**Comment by ComPieter1** [comment]
Tested with proxy and can confirm it works! Thank you.
